# Generated by Django 5.0.9 on 2025-12-06 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text="User's email address (unique identifier)", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(help_text="User's first name", max_length=50)),
                ('last_name', models.CharField(help_text="User's last name", max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line1', models.CharField(blank=True, help_text='Primary address line', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, help_text='Secondary address line (apartment, suite, etc.)', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State or province', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal or ZIP code', max_length=20, null=True)),
                ('country', models.CharField(default='USA', help_text='Country', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='user_profil_email_8a1024_idx'), models.Index(fields=['created_at'], name='user_profil_created_26443b_idx'), models.Index(fields=['is_active'], name='user_profil_is_acti_44246c_idx')],
            },
        ),
    ]
